### ISSUE TITLE
Tests are not passing

### ISSUE THREAD

**Issue by togakangaroo** [awspilot/cli-lambda-deploy#2]
On a fresh clone:

```bash
~/code/cli-lambda-deploy $ npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
added 46 packages from 507 contributors and audited 46 packages in 2.365s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
~/code/cli-lambda-deploy $ npm test

> aws-lambda@1.0.6 test /Users/gmauer/code/cli-lambda-deploy
> mocha --timeout 100000 -S -R spec --exit



  new-function JSON config
Lambda config not found (./test/res/new-function-json-v14.lambda )

/Users/gmauer/code/cli-lambda-deploy/node_modules/mocha/lib/runner.js:726
  err.uncaught = true;
               ^

TypeError: Cannot create property 'uncaught' on string 'process exit code 255'
    at Runner.uncaught (/Users/gmauer/code/cli-lambda-deploy/node_modules/mocha/lib/runner.js:726:16)
    at process.uncaught (/Users/gmauer/code/cli-lambda-deploy/node_modules/mocha/lib/runner.js:839:10)
    at process.emit (events.js:314:20)
    at process._fatalException (internal/process/execution.js:163:25)
npm ERR! Test failed.  See above for more details.
~/code/cli-lambda-deploy $ 
```

**Comment by adrianpraja** [comment]
Hi,

tests in the repository need credentials in the environment 
you would need to add your own access keys and `npm test` against your own aws account
